name: CI
on:
  push:
    branches: [main]
jobs:
  main:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: index.html
            destination: index.html
          - source: proposals/rdf-id.bs
            destination: specification/rdf-id.html
          - source: proposals/agent-specific-discovery.bs
            destination: specification/agent-specific-discovery.html
    name: Deploy to GitHub pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
