name: CI
on:
  push:
    branches: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11.1"

      - name: setup bikeshed
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade bikeshed
          bikeshed update

      - name: run bikeshed
        run: |
          bikeshed spec proposals/concepts-representation.bs
          bikeshed spec proposals/agent-specific-discovery.bs
          bikeshed spec proposals/data-discovery.bs

      - name: generate svg
        run: for diagram in proposals/diagrams/*.mmd; do docker run --rm -v "$PWD:/data" minlag/mermaid-cli -i /data/$diagram; done

      - name: run pandoc
        uses: docker://pandoc/latex:latest
        with:
          args: "./notes/response-tim-ruben.md -so ./notes/response-tim-ruben.html"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./proposals
          destination_dir: ./specification
          personal_token: ${{ secrets.GITHUB_TOKEN }}
